project:
  type: website
  output-dir: docs

website:
  title: "TC#2"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: outputs.qmd
        text: Outputs
      - href: actions.qmd
        text: Actions Required

format:
  html:
    theme:
      light: litera
      dark: slate
    css: styles.css
    toc: true
  pdf:
    documentclass: report
  docx: default
  pptx: default
    



